# This is a basic workflow to help you get started with Actions

name: Update Tistory Blog Post

# Controls when the workflow will run
on:
# 1시간에 한번씩 아래 스크립트를 실행한다.
  schedule:
    - cron: "* */1 * * *"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Update Post
        run: npm start
      - name: Commit Post
        run: |
          git add .
          git config --local user.email "worldsource93@naver.com"
          git config --local user.name "worldsource93"
          git commit -m "Update Tistory Blog Post"
          git push origin main
